apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-deployment
spec:
  scaleTargetRef:
    apiVersion: apiVersion
    kind: kind
    name: metadataname
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50