services:
  tgdb:
    build: ./mysql
    container_name: tgdb
  tgtraffic:
    build: ./nginx
    container_name: tgtraffic
    depends_on:
    - tgweb
  tgweb:
    build: ./UC
    container_name: tgweb
    depends_on:
    - tgdb
version: "3"
