---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ../lib/bin/kompose convert -f ../lib/bin/docker-compose.yaml --stdout
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: tgtraffic
  name: tgtraffic
spec:
  ports:
  - name: "5005"
    port: 5005
    targetPort: 5005
  selector:
    io.kompose.service: tgtraffic
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ../lib/bin/kompose convert -f ../lib/bin/docker-compose.yaml --stdout
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: tgtraffic
  name: tgtraffic
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: tgtraffic
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: ../lib/bin/kompose convert -f ../lib/bin/docker-compose.yaml --stdout
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: tgtraffic
    spec:
      containers:
      - image: damn/go_tgtraffic
        imagePullPolicy: Always
        name: tgtraffic
        ports:
        - containerPort: 5005
        resources: {}
        volumeMounts:
        - mountPath: /var/www/htmls
          name: tgtraffic-claim0
      imgaePullSecrets:
      - name: docker-secret
      restartPolicy: Always
      volumes:
      - name: tgtraffic-claim0
        persistentVolumeClaim:
          claimName: tgtraffic-claim0
status: {}
