apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ../lib/bin/kompose convert -f ../lib/bin/docker-compose.yaml --stdout
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: tgdb
  name: tgdb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: tgdb
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: ../lib/bin/kompose convert -f ../lib/bin/docker-compose.yaml --stdout
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: tgdb
    spec:
      containers:
      - image: damn/go_tgdb
        imagePullPolicy: Always
        name: tgdb
        ports:
        - containerPort: 3306
        resources:
          limits:
            cpu: 0.23272727272727273m
            memory: 454975.76727272733Ki
          requests:
            cpu: 0.14545454545454545m
            memory: 284359.85454545455Ki
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: tgdb-claim0
      imgaePullSecrets:
      - name: docker-secret
      restartPolicy: Always
      volumes:
      - name: tgdb-claim0
        persistentVolumeClaim:
          claimName: tgdb-claim0
status: {}
