apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-deployment-tgdb
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tgdb
  minReplicas: 2
  maxReplicas: 11
  targetCPUUtilizationPercentage: 50
